// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWtlJbTeKvS50jgizCadUzUH8-AEOt02M',
    appId: '1:246609540372:web:f2d28af43a575fd5b33e01',
    messagingSenderId: '246609540372',
    projectId: 'movies-app-b39ff',
    authDomain: 'movies-app-b39ff.firebaseapp.com',
    storageBucket: 'movies-app-b39ff.appspot.com',
    measurementId: 'G-ERTTY6J1PX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC47IPzuQnO5y2oKo9EJROuO_cSYDB8Yg',
    appId: '1:246609540372:android:8a9a5327616b27e2b33e01',
    messagingSenderId: '246609540372',
    projectId: 'movies-app-b39ff',
    storageBucket: 'movies-app-b39ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw4ZqCjOQb2qQyVfFTdYV_3Pn5NnspIhY',
    appId: '1:246609540372:ios:0d62d88c234e0f1ab33e01',
    messagingSenderId: '246609540372',
    projectId: 'movies-app-b39ff',
    storageBucket: 'movies-app-b39ff.appspot.com',
    iosClientId: '246609540372-5k882dfg2m32ne8g850dn5efbhnnirch.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw4ZqCjOQb2qQyVfFTdYV_3Pn5NnspIhY',
    appId: '1:246609540372:ios:0d62d88c234e0f1ab33e01',
    messagingSenderId: '246609540372',
    projectId: 'movies-app-b39ff',
    storageBucket: 'movies-app-b39ff.appspot.com',
    iosClientId: '246609540372-5k882dfg2m32ne8g850dn5efbhnnirch.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesApp',
  );
}
