// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw8IHSsS8yFHTu9fWkMLPWwwT2KHD-fBo',
    appId: '1:1078099840601:web:37edea2303047331f2eb48',
    messagingSenderId: '1078099840601',
    projectId: 'flutter-app-data',
    authDomain: 'flutter-app-data.firebaseapp.com',
    storageBucket: 'flutter-app-data.appspot.com',
    measurementId: 'G-KSQK38NT64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt5AY3TklQRwP3msXS2u9sk-0F5RqrBiM',
    appId: '1:1078099840601:android:9a12b3b72b682b8cf2eb48',
    messagingSenderId: '1078099840601',
    projectId: 'flutter-app-data',
    storageBucket: 'flutter-app-data.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEEwhLFfI3-h42V5LogilQR19jJvqZHb8',
    appId: '1:1078099840601:ios:a7c06a99109b85b8f2eb48',
    messagingSenderId: '1078099840601',
    projectId: 'flutter-app-data',
    storageBucket: 'flutter-app-data.appspot.com',
    iosClientId: '1078099840601-2too43vt15qbsum8n7ms9i52rjse9nof.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEEwhLFfI3-h42V5LogilQR19jJvqZHb8',
    appId: '1:1078099840601:ios:a7c06a99109b85b8f2eb48',
    messagingSenderId: '1078099840601',
    projectId: 'flutter-app-data',
    storageBucket: 'flutter-app-data.appspot.com',
    iosClientId: '1078099840601-2too43vt15qbsum8n7ms9i52rjse9nof.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesApp',
  );
}
